<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Title>Connect Provider Interface</Title>
    <Version>1.0.2026.10</Version>
    <Authors>Roberto Jucá (robjuca@pobox.com) Copyright © R&amp;R Soft 2001</Authors>
    <Company>R&amp;R Soft</Company>
    <Description>This .NET assembly is a library.</Description>
    <Copyright>R&amp;R Soft® is a registered trademark of R&amp;R Soft.</Copyright>
    <AssemblyName>Connect.Provider.Interface</AssemblyName>
    <BaseOutputPath>D:\GitHub\ShellConnect\Bin</BaseOutputPath>
    <OutputPath>D:\GitHub\ShellConnect\Bin</OutputPath>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="WpfEventDispatcherExtensions.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="desktop.ini" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Data\Provider.Data\Connect.Provider.Data.csproj" />
    <ProjectReference Include="..\..\Enumerator\Provider.Enumerator\Connect.Provider.Enumerator.csproj" />
  </ItemGroup>
</Project>