<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Title>Connect Process Dispatcher</Title>
		<Version>1.0.2026.10</Version>
		<Authors>Roberto Jucá (robjuca@pobox.com) Copyright © R&amp;R Soft 2001</Authors>
		<Company>R&amp;R Soft</Company>
		<Description>This .NET assembly is a library.</Description>
		<Copyright>R&amp;R Soft® is a registered trademark of R&amp;R Soft.</Copyright>
		<AssemblyName>Connect.Process.Dispatcher</AssemblyName>
		<OutputPath>D:\GitHub\ShellConnect\Bin</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="desktop.ini" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Caliburn.Micro.Core" Version="6.0.15-beta" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="Process\oldEventDispatcher.cs" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="Connect.Provider.Data">
	    <HintPath>..\..\..\Bin\Connect.Provider.Data.dll</HintPath>
	  </Reference>
	  <Reference Include="Connect.Provider.Enumerator">
	    <HintPath>..\..\..\Bin\Connect.Provider.Enumerator.dll</HintPath>
	  </Reference>
	  <Reference Include="Connect.Provider.Interface">
	    <HintPath>..\..\..\Bin\Connect.Provider.Interface.dll</HintPath>
	  </Reference>
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="xcopy &quot;$(TargetPath)&quot;  D:\SPAD.neXt\Addons /Y" />
	</Target>
</Project>